config/routes.rb
Gitaway::Application.routes.draw do

  resources :passwords,
    :controller => 'clearance/passwords',
    :only       => [:new, :create]

  resource  :session,
    :controller => 'clearance/sessions',
    :only       => [:new, :create, :destroy]

  resources :users, :controller => 'clearance/users', :only => [:new, :create] do
    resource :password,
      :controller => 'clearance/passwords',
      :only       => [:create, :edit, :update]

    resource :confirmation,
      :controller => 'clearance/confirmations',
      :only       => [:new, :create]
  end

  match 'sign_up'  => 'clearance/users#new', :as => 'sign_up'
  match 'sign_in'  => 'clearance/sessions#new', :as => 'sign_in'
  match 'sign_out' => 'clearance/sessions#destroy', :via => :delete, :as => 'sign_out'

  resources :u, :controller => 'u'

  resources :ssh_keys

  resources :repositories

  match 'repositories/:id/tree/:treeid', :controller => 'repositories', :action => 'tree'
  match 'repositories/:id/blob/:blobid', :controller => 'repositories', :action => 'blob'
  match 'repositories/:id/commits/:branch', :controller => 'repositories', :action => 'commits'
  match 'repositories/:id/commit/:commit', :controller => 'repositories', :action => 'commit'
  match 'repositories/:id/fork', :controller => 'repositories', :action => 'fork'
  match 'repositories/:id', :controller => 'repositories', :action => 'show'
  match 'repositories/:id/:branch', :controller => 'repositories', :action => 'show'
  match 'repositories/:id/:branch/*path', :controller => 'repositories', :action => 'show'

end

app/views/layouts/application.haml
%html{:xmlns => "http://www.w3.org/1999/xhtml", :lang => "en"}
  %head
    %title Gitaway
    = stylesheet_link_tag "reset","app","formtastic","formtastic_changes"
    -# javascript_include_tag :defaults
    = csrf_meta_tag


  %body
    #titlebar
      %h1 GitAway - Your personal hub for git
    #content{:class => @contentclass || "content"}
      - if current_user
        .logininfo== You are logged in as #{l current_user} (UserID: #{current_user.id})
        %p= link_to("Manage ssh keys",ssh_keys_path)
      =yield